### ISSUE TITLE
Disallowed Characters in labels

### ISSUE THREAD

**Issue by phillipengel** [IFRS-Foundation/issb-taxonomy#5]
[taxonomy_errors.xlsx](https://github.com/IFRS-Foundation/issb-taxonomy/files/14452540/taxonomy_errors.xlsx)

Attached is a list of concept with disallowed special characters. The disallowed characters come from the Review Guide A3.3. These characters are:

? | > < : * "+ = & @ { } \ ^ ¦

**Comment by oj-ifrs** [comment]
Simplest choice is to allow '&' , ':' and '"' . Tempted to replace double quotes with single however.
